"""add node table

Revision ID: 82ab217e5272
Revises: 
Create Date: 2023-07-05 17:21:47.548328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ab217e5272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('ipv4_address', sa.String(length=16), nullable=False),
    sa.Column('ipv6_address', sa.String(length=40), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('port', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_update_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nodes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_nodes_region'), ['region'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nodes_region'))
        batch_op.drop_index(batch_op.f('ix_nodes_name'))

    op.drop_table('nodes')
    # ### end Alembic commands ###
